name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306

      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - name: Install turbo globally
        run: bun -g add turbo
      - name: Install packages
        run: bun install

      - name: Set environment variables
        run: |
          echo "PG_DATABASE_URL=postgres://postgres:postgres@0.0.0.0:5432/testdb" >> $GITHUB_ENV
          echo "MYSQL_DATABASE_URL=mysql://root:mysql@0.0.0.0:3306/testdb" >> $GITHUB_ENV
      - name: Test
        run: turbo test
